CREATE TABLE IF NOT EXISTS ACCOUNTS (
  ACCOUNT_ID TEXT PRIMARY KEY,
  CREATED_AT TEXT DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS IDENTITIES (
  PROVIDER TEXT NOT NULL,
  PROVIDER_ID TEXT NOT NULL,
  ACCOUNT_ID TEXT NOT NULL,
  CREATED_AT TEXT DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (PROVIDER, PROVIDER_ID)
);
CREATE TABLE IF NOT EXISTS SESSIONS (
  SID TEXT PRIMARY KEY,
  ACCOUNT_ID TEXT NOT NULL,
  CREATED_AT TEXT DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS TOKENS (
  ACCOUNT_ID TEXT NOT NULL,
  SERVICE TEXT NOT NULL,
  ACCESS_TOKEN TEXT,
  REFRESH_TOKEN TEXT,
  EXPIRES_AT INTEGER,
  PRIMARY KEY (ACCOUNT_ID, SERVICE)
);
CREATE TABLE IF NOT EXISTS BOOKMARKS (
  TWEET_ID TEXT NOT NULL,
  ACCOUNT_ID TEXT NOT NULL,
  AUTHOR TEXT,
  TEXT TEXT,
  URL TEXT,
  MEDIA_TYPE TEXT,
  SYNCED_AT TEXT DEFAULT CURRENT_TIMESTAMP,
  STATUS TEXT,
  PRIMARY KEY (TWEET_ID, ACCOUNT_ID)
);
CREATE TABLE IF NOT EXISTS TODOS (
  ID TEXT PRIMARY KEY,
  ACCOUNT_ID TEXT NOT NULL,
  TWEET_ID TEXT,
  TITLE TEXT,
  CATEGORY TEXT,
  DONE INTEGER DEFAULT 0,
  CREATED_AT TEXT DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS EVENT_SUGGESTIONS (
  ID TEXT PRIMARY KEY,
  ACCOUNT_ID TEXT NOT NULL,
  TWEET_ID TEXT,
  TITLE TEXT,
  START_TS TEXT,
  DURATION_MIN INTEGER,
  ADDED INTEGER DEFAULT 0,
  CREATED_AT TEXT DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS INSIGHTS (
  ID TEXT PRIMARY KEY,
  ACCOUNT_ID TEXT NOT NULL,
  TWEET_ID TEXT,
  TEXT TEXT,
  CATEGORY TEXT,
  EVEROS_ID TEXT,
  CREATED_AT TEXT DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS SPEND_LOG (
  ID TEXT PRIMARY KEY,
  ACCOUNT_ID TEXT NOT NULL,
  CALL_TYPE TEXT,
  MODEL TEXT,
  PROMPT_TOKENS INTEGER,
  COMPLETION_TOKENS INTEGER,
  COST_USD REAL,
  CREATED_AT TEXT DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS EXT_TOKENS (
  TOKEN TEXT PRIMARY KEY,
  ACCOUNT_ID TEXT NOT NULL,
  CREATED_AT TEXT DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS SUBSCRIPTIONS (
  ACCOUNT_ID TEXT PRIMARY KEY,
  STRIPE_CUSTOMER_ID TEXT,
  STATUS TEXT,
  TRIAL_END INTEGER,
  CURRENT_PERIOD_END INTEGER,
  UPDATED_AT TEXT DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS IDX_TODOS_ACCOUNT ON TODOS (ACCOUNT_ID, DONE, CREATED_AT);
CREATE INDEX IF NOT EXISTS IDX_EVENTS_ACCOUNT ON EVENT_SUGGESTIONS (ACCOUNT_ID, ADDED, CREATED_AT);
CREATE INDEX IF NOT EXISTS IDX_INSIGHTS_ACCOUNT ON INSIGHTS (ACCOUNT_ID, CREATED_AT);
CREATE INDEX IF NOT EXISTS IDX_SPEND_ACCOUNT ON SPEND_LOG (ACCOUNT_ID, CREATED_AT);
